import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { keccak256, toHex } from "viem";
import { computeCcid, identifier } from "../src/credential-verify.js";

/**
 * Cross-language parity: the workflow's CCID derivation must equal the on-chain
 * resolver's, byte for byte.
 *
 * These vectors are generated by running `contracts/script/GenerateCcidVectors.s.sol`
 * against the real `CCIDResolver`, not written by hand. That distinction is the
 * whole point: a hand-copied vector would only prove the TypeScript matches what a
 * person typed, not that it matches the contract that will validate every credential
 * result this workflow produces.
 *
 * The vectors carry both the human-readable label and the derived `bytes32`,
 * because the workflow derives its identifiers from labels. Parity could not
 * otherwise be checked: the label cannot be recovered from the hash.
 */

interface Vector {
  credentialTypeLabel: string;
  providerIdLabel: string;
  subjectLabel: string;
  credentialType: string;
  schemaVersion: number;
  providerId: string;
  subjectCommitment: string;
  ccid: string;
}

const here = dirname(fileURLToPath(import.meta.url));
const vectorsFile = resolve(here, "vectors/ccid-vectors.json");
const payload = JSON.parse(readFileSync(vectorsFile, "utf8")) as { domain: string; vectors: Vector[] };

describe("identifier", () => {
  it("matches how the registries derive identifiers: keccak256 of the label", () => {
    expect(identifier("kyc.basic")).toBe(keccak256(toHex("kyc.basic")));
    expect(identifier("provider.reclaim")).toBe(keccak256(toHex("provider.reclaim")));
  });
});

describe("CCID parity with CCIDResolver.sol", () => {
  it("has vectors to check", () => {
    expect(payload.vectors.length).toBeGreaterThanOrEqual(8);
    expect(payload.domain).toMatch(/^0x[0-9a-f]{64}$/);
  });

  it("uses the same domain separator as the contract", () => {
    // keccak256("identity-bridge-zktls/CCID/v1")
    expect(payload.domain).toBe(keccak256(toHex("identity-bridge-zktls/CCID/v1")));
  });

  it("derives the same bytes32 identifiers the contract script used", () => {
    for (const v of payload.vectors) {
      expect(identifier(v.credentialTypeLabel).toLowerCase()).toBe(v.credentialType.toLowerCase());
      expect(identifier(v.providerIdLabel).toLowerCase()).toBe(v.providerId.toLowerCase());
    }
  });

  for (const [i, v] of payload.vectors.entries()) {
    it(`reproduces on-chain vector ${i + 1} (${v.credentialTypeLabel || "<empty>"}@v${v.schemaVersion})`, () => {
      const computed = computeCcid({
        domain: "identity-bridge-zktls/CCID/v1",
        credentialType: v.credentialTypeLabel,
        schemaVersion: v.schemaVersion,
        providerId: v.providerIdLabel,
        subjectCommitment: v.subjectCommitment,
      });
      expect(computed.toLowerCase()).toBe(v.ccid.toLowerCase());
    });
  }

  it("covers the widening edge cases, not just the happy path", () => {
    const byVersion = new Map(payload.vectors.map((v) => [v.schemaVersion, v]));
    expect(byVersion.has(0)).toBe(true); // zero schema version
    expect(byVersion.has(4294967295)).toBe(true); // max uint32
    // Empty labels are the boundary between a zero value and a real hash, which
    // is exactly where abi.encodePacked vs abi.encode would diverge.
    expect(payload.vectors.some((v) => v.providerIdLabel === "")).toBe(true);
    expect(payload.vectors.some((v) => v.subjectLabel === "")).toBe(true);
    expect(payload.vectors.some((v) => v.credentialTypeLabel === "")).toBe(true);
  });

  it("changes when any single input changes", () => {
    const base = payload.vectors[0]!;
    const args = {
      domain: "identity-bridge-zktls/CCID/v1",
      credentialType: base.credentialTypeLabel,
      schemaVersion: base.schemaVersion,
      providerId: base.providerIdLabel,
      subjectCommitment: base.subjectCommitment,
    };
    const original = computeCcid(args);
    expect(computeCcid({ ...args, schemaVersion: args.schemaVersion + 1 })).not.toBe(original);
    expect(computeCcid({ ...args, credentialType: "other" })).not.toBe(original);
    expect(computeCcid({ ...args, providerId: "other" })).not.toBe(original);
    expect(computeCcid({ ...args, subjectCommitment: keccak256(toHex("other")) })).not.toBe(original);
  });
});